name: "Prepare Percy build"

on:
  workflow_call:
    inputs: 
      pr_number:
        required: true
        type: number
      repository: 
        required: true
        type: string
      commitsh:
        required: true
        type: string

jobs:
  print_env:
    name: Report environment
    runs-on: ubuntu-latest
    steps:
      - name: Report GHA event name
        id: report_gha_event
        run: |
          echo "GHA event name: ${{ github.event_name }}"
          echo "GHA event action: ${{ github.event.action }}"
          echo "PR labels: ${{ github.event.pull_request.labels }}"
          echo "::set-output name=gha_event::${{ toJson(github.event) }}"
      - name: Report GHA event
        run: |
          echo "GHA event: ${{ steps.report_gha_event.outputs.gha_event }}"


  copy_artifact:
    name: Copy changed files to GHA artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            templates/docs/examples/
            scss/
          ref: ${{ github.event.inputs.commitsh }}
          repository: ${{ github.event.inputs.repository }}

      - name: Populate artifact directory
        run: |
          mkdir -p artifact
          cp -R templates/docs/examples/ scss/ artifact/.
        
      # Archive the PR number associated with this workflow since it won't be available in the base workflow context
      # https://github.com/orgs/community/discussions/25220
      - name: Archive PR data
        if: github.event_name=='pull_request'
        working-directory: artifact
        run: |
          echo ${{ inputs.pr_number }} > pr_num.txt
          echo ${{ inputs.commitsh }} > pr_head_sha.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "percy-testing-web-artifact"
          path: artifact/*