name: "Prepare Percy build on Percy - push"

on:
  pull_request:
    branches:
      - main
    paths:
      - "templates/docs/examples/**"
      - "scss/**"
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened

jobs:
  copy_artifact:
    name: Copy changed files to GHA artifact
    # Ignore draft PRS and PRs with the Percy label
    # If we run tests against PRs with the Percy label, we will run tests twice (test is also ran by the labelling workflow)
    if: ${{ !github.event.pull_request.draft && !contains(github.event.pull_request.labels.*.name, vars.PERCY_TEST_REQUESTED_LABEL_NAME) }}
    uses: ./.github/workflows/percy-prepare.yml
    with:
      pr_number: ${{ github.event.number }}
      repository: ${{ github.repository }}
      commitsh: ${{ github.event.pull_request.head.sha }}